### ISSUE TITLE
secrets in db should be encrypted

### ISSUE THREAD

**Issue by dannydeezy** [Uthpala/tao-wallet-web#1]
one thing we could do is separate the concerns:
- encrypt them with an AWS KMS key that i control
- store them in the DB that @Uthpala controls

**Comment by uthpalax** [comment]
Yup like we discussed we can use [fly secrets](https://fly.io/docs/reference/secrets/)
I have added you to the project in fly. 
I was thinking you set up a secret ENCRYPTION_KEY_1 and I set up ENCRYPTION_KEY_2 
Then I will update the project code to encrypt using both keys. 
I have locked the main branch and added you as a collaborator to the repo. I will update the settings so that only PR's that are approved by you and me both can be merged. 

fly secrets has a digest string. Lets have copies of those and make sure those do not change. If they change that means one of us has reset them.
